In [82]:
def hardLevel(ledPinYellow, ledPinGreen, ledPinBlue, ledPinRed, counter, buttonYellow, buttonGreen, buttonBlue, buttonRed):
    # 2*counter + 3 = c2
    #^ for (i , i<c2, i++)
    # add to list in order of leds
    # increase speed sleeper 
    
    #while buttons after one is pressed compare to list at that position
    
    # return true or false
    rng = np.random.default_rng(54271)
    
    c2 = 2*counter + 5  # counter + 3 = c2
    yel = 1
    green = 2
    blue = 3
    red = 4
    i = 0
    t_count = 0
    new_list = []
    print("hard")
    
    ledPattern = rng.integers(low=1, high=5, size=c2) #creates an array of numbers based on our led numbers
    
    for led in ledPattern: # then loops through the array and turning on certain leds baised on the array of numbers
        if led == yel:
            GPIO.output(ledPinYellow, True)
            time.sleep(0.5)
            GPIO.output(ledPinYellow, False)
        elif led == green:
            GPIO.output(ledPinGreen, True)
            time.sleep(0.5)
            GPIO.output(ledPinGreen, False)
        elif led == blue:
            GPIO.output(ledPinBlue, True)
            time.sleep(0.5)
            GPIO.output(ledPinBlue, False)
        else:
            GPIO.output(ledPinRed, True)
            time.sleep(0.5)
            GPIO.output(ledPinRed, False)
    print(ledPattern)
    while True: 
        if t_count == len(ledPattern):
            print('break')
            break
        if (GPIO.input(buttonYellow) == 1):
            new_list.append(yel)
            t_count += 1
            print("y")
        elif (GPIO.input(buttonGreen) == 1):
            new_list.append(green)
            t_count += 1
            print('g')
        elif (GPIO.input(buttonBlue) == 1):
            new_list.append(blue)
            t_count += 1
            print("b")
        elif (GPIO.input(buttonRed) == 1):
            new_list.append(red)
            t_count += 1
            print("r")
            #if ((GPIO.input(ledPinYellow) == 1) and (order == yel)) or ((GPIO.input(ledPinGreen) == 1) and (order == green)) or ((GPIO.input(ledPinBlue) == 1) and (order == blue)) or ((GPIO.input(ledPinRed) == 1) and (order == red)): 
                #continue #if the correct button is pressed then continue going into the array
        time.sleep(.25)
    for i in range(len(ledPattern)):
        if new_list[i] != ledPattern[i]:
            return True
        
    return False    
        
        
        
    
    
def easyLevel(ledPinYellow, ledPinGreen, ledPinBlue, ledPinRed, counter, buttonYellow, buttonGreen, buttonBlue, buttonRed):
    print("easy")
    rng = np.random.default_rng(12345)
    new_list = []
    c2 = counter + 3  # counter + 3 = c2
    yel = 1
    green = 2
    blue = 3
    red = 4
    i = 0
    t_count = 0
    
    ledPattern = rng.integers(low=1, high=5, size=c2) #creates an array of numbers based on our led numbers
    
    for led in ledPattern: # then loops through the array and turning on certain leds baised on the array of numbers
        if led == yel:
            GPIO.output(ledPinYellow, True)
            time.sleep(0.5)
            GPIO.output(ledPinYellow, False)
        elif led == green:
            GPIO.output(ledPinGreen, True)
            time.sleep(0.5)
            GPIO.output(ledPinGreen, False)
        elif led == blue:
            GPIO.output(ledPinBlue, True)
            time.sleep(0.5)
            GPIO.output(ledPinBlue, False)
        else:
            GPIO.output(ledPinRed, True)
            time.sleep(0.5)
            GPIO.output(ledPinRed, False)
            
    print(ledPattern)
    #for order in ledPattern: #loop through the ledPattern array and see if the correct button input is done 
    
    print(t_count)
    while True: 
        if t_count == len(ledPattern):
            print('break')
            break
        if (GPIO.input(buttonYellow) == 1):
            new_list.append(yel)
            t_count += 1
            print("y")
        elif (GPIO.input(buttonGreen) == 1):
            new_list.append(green)
            t_count += 1
            print('g')
        elif (GPIO.input(buttonBlue) == 1):
            new_list.append(blue)
            t_count += 1
            print("b")
        elif (GPIO.input(buttonRed) == 1):
            new_list.append(red)
            t_count += 1
            print("r")
            #if ((GPIO.input(ledPinYellow) == 1) and (order == yel)) or ((GPIO.input(ledPinGreen) == 1) and (order == green)) or ((GPIO.input(ledPinBlue) == 1) and (order == blue)) or ((GPIO.input(ledPinRed) == 1) and (order == red)): 
                #continue #if the correct button is pressed then continue going into the array
        time.sleep(.25)

    for i in range(len(ledPattern)):
        if new_list[i] != ledPattern[i]:
            return True
        
    return False 

def wrongCorrectSong(buzPin1, frequency, duration):
    duty = .5
    for i in range(len(frequency)): 
        # turn the buzzer on
        pi.hardware_PWM(buzPin1, int(frequency[i]), int(duty * 1e6))
        time.sleep(duration[i])
    # turn the buzzer off
    pi.hardware_PWM(buzPin1, 0, 0)
    

In [83]:
import numpy as np
#frequency of notes for the "correct" chime
#freqs_cor = [349, 294, 392]

#beats for each note in "correct" chime
#beats_cor = [.5, .25, 1]
cor = ([[349, .5], [294, .25], [392, 1]])
np.save('correctSong.npy', cor)
inc = ([[349, .5], [294, .5], [277, .5], [262, .5]])
np.save('wrongSong.npy', inc)
#song beats per minute
#bpm = 168

#convert the times into seconds
#times_cor = [ibeat/bpm * 60 for ibeat in beats_cor]

#create the np array
#final_cor = np.array([freqs_cor, times_cor], dtype = 'float')

#transpose the array
#final_cor = final_cor.transpose()

#save data to file
#np.save('correctSong.npy', final_cor)

#frequency of notes for the "incorrect" chime
#freqs_inc = [349, 294, 277, 262]

#beats for each note in "incorrect" chime
#beats_inc = [.5, .5, .5, .5]

#song beats per minute
#bpm = 168

#convert the times into seconds
#times_inc = [ibeat/bpm * 60 for ibeat in beats_inc]

#create the np array
#final_inc = np.array([freqs_inc, times_inc], dtype = 'float')

#transpose the array
#final_inc = final_inc.transpose()

#save data to file
#np.save('wrongSong.npy', final_inc)


In [84]:
import numpy as np
import RPi.GPIO as GPIO
import adcUtil as adc
import time
import pigpio

# create reference to pigpio daemon
pi = pigpio.pi(port = 8887)

# setup GPIO as input for the gate pin
GPIO.setmode(GPIO.BCM)
switchPin = 26
buzPin1 = 12

buttonYellow = 24
buttonGreen = 18
buttonBlue = 22
buttonRed = 19

#make sure that the GPIO is set up 
GPIO.setup(buttonYellow, GPIO.IN, pull_up_down = GPIO.PUD_DOWN)
print(GPIO.input(buttonYellow))
GPIO.setup(buttonGreen, GPIO.IN, pull_up_down = GPIO.PUD_DOWN)
print(GPIO.input(buttonGreen))
GPIO.setup(buttonBlue, GPIO.IN, pull_up_down = GPIO.PUD_DOWN)
print(GPIO.input(buttonBlue))
GPIO.setup(buttonRed, GPIO.IN, pull_up_down = GPIO.PUD_DOWN)
print(GPIO.input(buttonRed))

# assign a variable for the pin number
ledPinYellow = 13
ledPinGreen = 21
ledPinBlue = 16
ledPinRed = 20

# set the GPIO pin to output mode
GPIO.setup(ledPinYellow, GPIO.OUT)
GPIO.setup(ledPinGreen, GPIO.OUT)
GPIO.setup(ledPinBlue, GPIO.OUT)
GPIO.setup(ledPinRed, GPIO.OUT)

#set up wrong and correct sounds
cdata = np.load("correctSong.npy")
correctFrequency = cdata[:,0]
correctDuration = cdata[:,1]

wdata = np.load("wrongSong.npy")
wrongFrequency = wdata[:,0]
wrongDuration = wdata[:,1]

0
0
0
0


In [ ]:
Vin =  3.3 # Volt
R2  = 10.0 # kOhm
R1 = 0

wL = False #if you lose it becomes true

Vou = adc.readADC(channel=1,device=0) # flex sensor voltage
if(Vou != 0):
    R1 = R2 * (Vin/Vou - 1)                # flex sensor resistance
    Rflex = 10 + R1; 
    
    
while True:
    #Get flex sensors resistor 
    Vou = adc.readADC(channel=1,device=1) # flex sensor voltage
    if(Vou != 0):
        R1 = R2 * (Vin/Vou - 1)                # flex sensor resistance 
    #if it is bent
    if R1 < Rflex:
        counter = 0  #only want to do this acertain amonent of times
        GPIO.setup(switchPin, GPIO.IN, pull_up_down = GPIO.PUD_UP)
        if (GPIO.input(switchPin) == 0): # if mag is connected to reed switch then send to hard Level
            print("mag")
            while (counter < 5) and (wL == False):
                wL = hardLevel(ledPinYellow, ledPinGreen, ledPinBlue, ledPinRed, counter, buttonYellow, buttonGreen, buttonBlue, buttonRed)
                if(wL == True):
                    wrongCorrectSong(buzPin1, wrongFrequency*2, wrongDuration) #buzzer plays wrong noise and breaks from loop
                    break
                else:
                    wrongCorrectSong(buzPin1, correctFrequency*2, correctDuration) #buzzer plays correct noise and continues in loop
                    counter +=1
            break
        else:# if mag is not connected to reed switch then send to easy level
            while (counter < 5) and (wL == False):  
                wL = easyLevel(ledPinYellow, ledPinGreen, ledPinBlue, ledPinRed, counter, buttonYellow, buttonGreen, buttonBlue, buttonRed)
                if(wL == True):
                    print("wrong")
                    wrongCorrectSong(buzPin1, wrongFrequency*2, wrongDuration) #buzzer plays wrong noise and breaks from loop
                    break
                    
                else:
                    print("correct")
                    wrongCorrectSong(buzPin1, correctFrequency*2, correctDuration) #buzzer plays correct noise and continues in loop
                    counter +=1
            break
    


mag
hard
[2 1 2 1 2]
g
y
g
y
g
break
hard
[2 1 2 1 2 3 3]
g
y
g
y
g
b
b
break
hard
[2 1 2 1 2 3 3 2 3]
g
y
g
y
g
b
b
g
b
break
hard
[2 1 2 1 2 3 3 2 3 4 4]


In [81]:
GPIO.cleanup()

## 